using Avalonia.Controls;
using Avalonia.Input;
using Avalonia.Interactivity;
using Babelive.Translation;
using MsBox.Avalonia;
using MsBox.Avalonia.Enums;
using MsbIcon = MsBox.Avalonia.Enums.Icon;

namespace Babelive;

/// <summary>
/// Modal dialog for editing the API endpoint base URL and API key.
/// On Save, mutates the supplied <see cref="AppSettings"/> in place AND
/// persists to <c>%APPDATA%\Babelive\settings.json</c>; on Cancel,
/// the supplied settings instance is left untouched.
///
/// Closes with a bool result: <c>true</c> = saved, <c>false</c> =
/// cancelled. The caller uses <c>await ShowDialog&lt;bool&gt;(owner)</c>.
/// </summary>
public partial class ApiSettingsWindow : Window
{
    private readonly AppSettings _settings;

    // Parameterless ctor required by Avalonia's XAML compiler when there's
    // no explicit constructor wiring — but we always construct via the
    // settings-taking overload. Marked obsolete so it's never picked.
    [Obsolete("Use the AppSettings-taking constructor.", error: true)]
    public ApiSettingsWindow() : this(new AppSettings()) { }

    public ApiSettingsWindow(AppSettings settings)
    {
        // InitializeComponent() is generated by Avalonia's XamlIl compiler
        // — don't override or x:Name fields won't be assigned.
        InitializeComponent();
        _settings = settings;
        BaseUrlBox.Text = string.IsNullOrWhiteSpace(settings.BaseUrl)
            ? RealtimeTranslatorClient.DefaultBase
            : settings.BaseUrl;
        ApiKeyBox.Text = settings.ApiKey ?? string.Empty;
    }

    private async void SaveBtn_Click(object? sender, RoutedEventArgs e)
    {
        _settings.BaseUrl = string.IsNullOrWhiteSpace(BaseUrlBox.Text)
            ? null : BaseUrlBox.Text!.Trim();
        _settings.ApiKey  = string.IsNullOrWhiteSpace(ApiKeyBox.Text)
            ? null : ApiKeyBox.Text!.Trim();
        try
        {
            _settings.Save();
            Close(true);
        }
        catch (Exception ex)
        {
            await MessageBoxManager.GetMessageBoxStandard(
                "Save failed",
                $"Failed to save settings to:\n{AppSettings.FilePath}\n\n{ex.Message}",
                ButtonEnum.Ok, MsbIcon.Warning).ShowWindowDialogAsync(this);
        }
    }

    private void CancelBtn_Click(object? sender, RoutedEventArgs e)
        => Close(false);

    // Drag the title-bar grid to move the window — Avalonia's equivalent
    // of WPF's WindowChrome caption area.
    private void TitleBar_PointerPressed(object? sender, PointerPressedEventArgs e)
    {
        if (e.GetCurrentPoint(this).Properties.IsLeftButtonPressed)
            BeginMoveDrag(e);
    }
}
