using Avalonia;
using Avalonia.Controls;
using Avalonia.Input;
using Avalonia.Interactivity;
using Avalonia.Threading;
using MsBox.Avalonia;
using MsBox.Avalonia.Enums;
using MsbIcon = MsBox.Avalonia.Enums.Icon;

namespace Babelive;

/// <summary>
/// Transparent always-on-top "desktop lyrics" overlay. Source-language
/// sentence on a small dim line above, larger gradient-filled translation
/// below, with a faked 4-direction outline and soft glow. Drag-to-move
/// with a 3 px hysteresis (so we don't break double-click). Bottom-right
/// grip resizes via the OS via BeginResizeDrag.
/// </summary>
public partial class LyricWindow : Window
{
    private readonly MainWindow _settings;

    // Cap each rolling buffer well within what fits at the default font
    // size, so the Viewbox never shrinks the text down.
    private const int MaxTargetChars = 30;
    private const int MaxSourceChars = 55;
    private string _sourceBuf = string.Empty;
    private string _targetBuf = string.Empty;

    // Translation font size (user-adjustable via A−/A+ buttons)
    private double _translationFontSize = 34;
    private const double MinFontSize = 18;
    private const double MaxFontSize = 64;
    private const double FontStep = 2;

    // Parameterless ctor — only here to satisfy Avalonia's XAML runtime-
    // loader warning (AVLN3001). The app always constructs via the
    // settings-taking overload from App.axaml.cs.
    [Obsolete("Use LyricWindow(MainWindow). This ctor exists only for the XAML loader.", error: true)]
    public LyricWindow() : this(null!) { }

    public LyricWindow(MainWindow settings)
    {
        // InitializeComponent() is generated by Avalonia's XamlIl compiler
        // — don't override or x:Name fields won't be assigned.
        InitializeComponent();
        _settings = settings;
        PositionAtBottomCenter();

        _settings.OnSourceDelta     += OnSourceDelta;
        _settings.OnTranslatedDelta += OnTranslatedDelta;
        _settings.OnRunningChanged  += UpdateToggleLabel;
        UpdateToggleLabel();
    }

    private void PositionAtBottomCenter()
    {
        // WorkingArea excludes the taskbar; sit flush with its top edge.
        var screen = Screens.ScreenFromWindow(this) ?? Screens.Primary;
        if (screen == null) return;
        var wa = screen.WorkingArea;
        var scaling = screen.Scaling;
        // WorkingArea is in physical pixels; Window.Position is in physical
        // pixels too, but Width/Height are device-independent units. Scale
        // up before computing the offset.
        Position = new PixelPoint(
            wa.X + (int)((wa.Width  - Width  * scaling) / 2),
            wa.Y +  wa.Height - (int)(Height * scaling));
    }

    // ---- hover: fade toolbar + hover frame -------------------------------
    // Avalonia uses declarative Transitions (set up in XAML on the elements)
    // — we just flip Opacity and the transition animates the change.
    private void Window_PointerEntered(object? sender, PointerEventArgs e)
    {
        Toolbar.Opacity    = 1.0;
        HoverFrame.Opacity = 1.0;
        ResizeGrip.Opacity = 1.0;
    }

    private void Window_PointerExited(object? sender, PointerEventArgs e)
    {
        Toolbar.Opacity    = 0.0;
        HoverFrame.Opacity = 0.0;
        // Grip stays faintly visible so the user can still see where to grab.
        ResizeGrip.Opacity = 0.4;
    }

    // ---- drag to move + double-click-snap --------------------------------
    // Double-click detection uses Avalonia's PointerPressedEventArgs.ClickCount
    // (it's already debounced by the OS click-time), so we don't need a manual
    // "_lastClickAt + 350 ms window" check like the WPF version had.
    private bool _maybeStartDrag;
    private Point _maybeDragStartPos;
    private const double DragHysteresisPx = 3;
    private const double TopStripPx = 50;

    private void Window_PointerPressed(object? sender, PointerPressedEventArgs e)
    {
        var pt = e.GetCurrentPoint(this);
        if (!pt.Properties.IsLeftButtonPressed) return;
        var pos = pt.Position;

        // Avalonia exposes ClickCount on PointerPressedEventArgs, similar to
        // WPF. Use it for double-click-snap in the top empty strip.
        if (e.ClickCount == 2 && pos.Y < TopStripPx)
        {
            DoSnapToggle();
            _maybeStartDrag = false;
            e.Handled = true;
            return;
        }

        // Single click — arm a deferred drag (don't BeginMoveDrag eagerly,
        // it'd swallow the next mouse-up and break double-click detection).
        _maybeStartDrag = true;
        _maybeDragStartPos = pos;
    }

    private void Window_PointerMoved(object? sender, PointerEventArgs e)
    {
        if (!_maybeStartDrag) return;
        var pt = e.GetCurrentPoint(this);
        if (!pt.Properties.IsLeftButtonPressed)
        {
            _maybeStartDrag = false;
            return;
        }
        var pos = pt.Position;
        if (Math.Abs(pos.X - _maybeDragStartPos.X) > DragHysteresisPx ||
            Math.Abs(pos.Y - _maybeDragStartPos.Y) > DragHysteresisPx)
        {
            _maybeStartDrag = false;
            try { BeginMoveDrag(e as PointerPressedEventArgs ?? null!); }
            catch { /* BeginMoveDrag needs PointerPressed args */ }
        }
    }

    private void Window_PointerReleased(object? sender, PointerReleasedEventArgs e)
    {
        _maybeStartDrag = false;
    }

    private void DoSnapToggle()
    {
        var screen = Screens.ScreenFromWindow(this) ?? Screens.Primary;
        if (screen == null) return;
        var wa = screen.WorkingArea;
        var scaling = screen.Scaling;
        int widthPx  = (int)(Width  * scaling);
        int heightPx = (int)(Height * scaling);

        int newX = wa.X + (wa.Width - widthPx) / 2;
        double midY = wa.Y + wa.Height / 2.0;
        double centerY = Position.Y + heightPx / 2.0;
        int newY = centerY < midY
            ? wa.Y + wa.Height - heightPx   // currently top half → flip to bottom
            : wa.Y;                          // currently bottom half → flip to top
        Position = new PixelPoint(newX, newY);
    }

    // ---- bottom-right resize grip ----------------------------------------
    // Avalonia's BeginResizeDrag works on transparent windows (unlike WPF),
    // so we can use the OS resize loop rather than tracking mouse-deltas
    // manually like the WPF version did.
    private void ResizeGrip_PointerPressed(object? sender, PointerPressedEventArgs e)
    {
        if (!e.GetCurrentPoint(this).Properties.IsLeftButtonPressed) return;
        try { BeginResizeDrag(WindowEdge.SouthEast, e); }
        catch { /* transient — wrong edge in event */ }
        e.Handled = true;
    }

    // ---- toolbar buttons -------------------------------------------------
    private async void ToggleBtn_Click(object? sender, RoutedEventArgs e)
    {
        try { await _settings.ToggleRunningAsync(); }
        catch (Exception ex)
        {
            await MessageBoxManager.GetMessageBoxStandard(
                "Toggle failed", ex.Message, ButtonEnum.Ok, MsbIcon.Warning)
                .ShowWindowDialogAsync(this);
        }
    }

    private void SettingsBtn_Click(object? sender, RoutedEventArgs e)
    {
        if (!_settings.IsVisible) _settings.Show();
        if (_settings.WindowState == WindowState.Minimized)
            _settings.WindowState = WindowState.Normal;
        _settings.Activate();
    }

    private void HideBtn_Click(object? sender, RoutedEventArgs e) => Hide();

    private void FontMinusBtn_Click(object? sender, RoutedEventArgs e)
    {
        _translationFontSize = Math.Max(MinFontSize, _translationFontSize - FontStep);
        TranslationText.FontSize = _translationFontSize;
    }

    private void FontPlusBtn_Click(object? sender, RoutedEventArgs e)
    {
        _translationFontSize = Math.Min(MaxFontSize, _translationFontSize + FontStep);
        TranslationText.FontSize = _translationFontSize;
    }

    private const float VolumeStep = 0.10f;
    private void VolDownBtn_Click(object? sender, RoutedEventArgs e)
    {
        _settings.TranslationVolume = _settings.TranslationVolume - VolumeStep;
        ShowVolumeFlash();
    }
    private void VolUpBtn_Click(object? sender, RoutedEventArgs e)
    {
        _settings.TranslationVolume = _settings.TranslationVolume + VolumeStep;
        ShowVolumeFlash();
    }

    private void ShowVolumeFlash()
    {
        var pct = (int)Math.Round(_settings.TranslationVolume * 100);
        var prev = SourceText.Text;
        var flash = $"♪ {pct}%";
        SourceText.Text = flash;
        Dispatcher.UIThread.InvokeAsync(async () =>
        {
            await Task.Delay(900);
            if (SourceText.Text == flash)
                SourceText.Text = prev;
        });
    }

    // ---- text streaming --------------------------------------------------
    private void OnSourceDelta(string delta)
    {
        Dispatcher.UIThread.Post(() =>
        {
            _sourceBuf = AppendAndTrim(_sourceBuf, delta, MaxSourceChars);
            SourceText.Text = _sourceBuf;
        });
    }

    private void OnTranslatedDelta(string delta)
    {
        Dispatcher.UIThread.Post(() =>
        {
            _targetBuf = AppendAndTrim(_targetBuf, delta, MaxTargetChars);
            TranslationText.Text = _targetBuf;
        });
    }

    private static string AppendAndTrim(string buf, string delta, int maxChars)
    {
        buf += delta;
        if (buf.Length <= maxChars) return buf;

        int keepStart = buf.Length - maxChars;
        int sentenceEnd = -1;
        for (int i = keepStart; i < buf.Length - 4; i++)
        {
            char c = buf[i];
            if (c == '。' || c == '.' || c == '?' || c == '?'
                || c == '!' || c == '!' || c == ';' || c == ';')
            { sentenceEnd = i; break; }
        }
        return sentenceEnd >= 0 ? buf[(sentenceEnd + 1)..].TrimStart() : buf[keepStart..];
    }

    public void UpdateToggleLabel()
    {
        Dispatcher.UIThread.Post(() =>
        {
            ToggleBtn.Content = _settings.IsRunning ? "■ Stop" : "▶ Start";
        });
    }

    protected override void OnClosed(EventArgs e)
    {
        _settings.OnSourceDelta     -= OnSourceDelta;
        _settings.OnTranslatedDelta -= OnTranslatedDelta;
        _settings.OnRunningChanged  -= UpdateToggleLabel;
        base.OnClosed(e);
    }
}
